### ISSUE TITLE
Can ranges have lengths?

### ISSUE THREAD

**Issue by berquist** [isi-vista/vistautils#29] opened 2018-11-26 15:36 UTC
[`span`s have a length.](https://github.com/isi-vista/vistautils/blob/c18b64b6750beb42583a90d0fc0224d8435842af/vistautils/span.py#L81) For the instances where one of the bounds is an infinity, assuming you don't want external dependencies, something like `ValueError` can be raised.

**Comment by rgabbard** [comment] 2018-11-27 14:41
@berquist : The problem is that `Range` works over an arbitrary `T` which supports comparison, but we don't make any further requirement that would allow us to calculate lengths.  (for example, you could have a `Range.open("hello", "world")` which includes all strings between those two in comparison order.  It is not clear what the length of this span would be.

**Comment by rgabbard** [comment] 2018-11-30 16:49
@berquist : Are you satisfied with this explanation? If so, can you close the issue?

**Comment by berquist** [comment] 2018-11-30 17:04
I have not had time to think about it yet, so my cursory response is that I am not satisfied; Constantine told me I should check the Guava docs for how they do it.

**Comment by rgabbard** [comment] 2018-11-30 17:07
Sure, take your time.  In Guava, `Range`s have no `.size()`.  However, you can pair a `Range` with a `DiscreteDomain` to produce a `ContiguousSet`, which does have a `.size()`.

**Comment by rgabbard** [comment] 2019-02-01 19:22
@berquist : checking in to see if you are satisfied now. :-) . Or do you want to turn this into a feature request to introduce something like `DiscreteDomain`?

**Comment by berquist** [comment] 2019-02-04 17:00
I see the problem now, so yes, I am mostly satisfied. What I would be looking for is additions to `DiscreteDomain<Integer>` (the Java type). Both `BigInteger` (Java) and `int` (Python) would allow for creation of infinite domains, which is something outside the use case I was thinking of.

This was an XY problem; I wanted to take intersections of `Span`s, which required dropping down to `Range`s. Why is `Span` not a bound-restricted subclass of `Range`?

**Comment by rgabbard** [comment] 2019-02-04 17:03
> Why is Span not a bound-restricted subclass of Range

In part, efficiency.  `Span` can just hold two `int`s, but `Ranges` hold two `_Cut` objects, which require another layer of object wrapping and access. Since `Spans` are such frequently used and fundamental objects in NLP (including in inner loops), we wanted to have a faster and more compact representation.

**Closed** 2019-02-04 17:04 UTC
Labels: question
